dist: focal
language: php

services:
  - docker

php:
  - 8.0

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 8.0
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_install:
  - docker run -d -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.12.0

before_script:
  - sleep 30
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  # - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
